name: flutter_application_1
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  go_router: ^14.0.0
  provider: ^6.0.2
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^10.0.0
  speedometer_chart: ^1.0.8
  english_words: ^4.0.0
  flutter_chat_ui: ^1.6.14
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  google_sign_in: ^6.2.0
  http: ^1.2.2
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  stylish_bottom_bar: ^1.1.0
  lottie: ^3.1.2
  uuid: ^4.4.2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0
  fluttertoast: ^8.0.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/brain.png
    - assets/images/search_icon.png
    - assets/images/notification_icon.png
    - assets/images/morning_icon.png
    - assets/images/angry_icon.png
    - assets/images/cry_icon.png
    - assets/images/sad_icon.png
    - assets/images/shy_icon.png
    - assets/images/smile_icon.png
    - assets/images/smile_with_pain_icon.png
    - assets/images/thinking_icon.png
    - assets/images/reminder_icon.png
    - assets/images/chat_bot_anim.json
    - assets/images/star.png
    - assets/images/three_dot_loader.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/APP_ICON.webp"
